plugins:
  spotocean:
    executor: central_deployment_agent
    package_name: cloudify-spot-ocean-plugin
    package_version: 0.0.5
data_types:
  cloudify.datatypes.SpotOcean.ConnectionConfig:
    properties:
      account_id:
        type: string
        required: true
      spot_ocean_token:
        type: string
        required: true
  cloudify.datatypes.SpotOcean.Cluster.config:
    properties:
      OceanClusterName:
        type: string
        required: true
      ClusterId:
        type: string
        required: true
      Region:
        type: string
        required: true
      InstanceTypes:
        type: string
        default: t3.medium
      SecurityGroupIds:
        type: list
        required: true
      ImageId:
        type: string
        required: false
      KeyPair:
        type: string
        required: true
      SubnetIds:
        type: list
        required: true
      MinCapacity:
        type: integer
        default: 1
      MaxCapacity:
        type: integer
        default: 1
      TargetCapacity:
        type: integer
        default: 1
      kwargs:
        default: {}
  cloudify.datatypes.SpotOcean.AWSConnectionConfig:
    properties:
      aws_session_token:
        type: string
        required: false
      aws_access_key_id:
        type: string
        required: false
      aws_secret_access_key:
        type: string
        required: false
      region_name:
        type: string
        required: false
dsl_definitions:
  client_config:
    client_config: &id001
      type: cloudify.datatypes.SpotOcean.ConnectionConfig
  aws_config:
    aws_config: &id002
      type: cloudify.datatypes.SpotOcean.AWSConnectionConfig
node_types:
  cloudify.nodes.SpotOcean.cluster:
    derived_from: cloudify.nodes.Root
    properties:
      client_config: *id001
      aws_config: *id002
      resource_config:
        type: cloudify.datatypes.SpotOcean.Cluster.config
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: spotocean.cloudify_spot_ocean.tasks.create
        delete:
          implementation: spotocean.cloudify_spot_ocean.tasks.delete
