version: 2.1

orbs:
  node: cloudify/public-unittest-orb@1 #orb version
  wagonorb: cloudify/wagon-bulder-orb@2 #orb version
  releaseorb: cloudify/release-orb@1 #orb version
  managerorb: cloudify/manager-orb@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  py36:
    docker:
      - image: circleci/python:3.6

  cloudify-machine-py3:
    machine:
      image: ubuntu-2004:202201-02

commands:
  prepare_test_manager:
    steps:
      - run: ls -alR
      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es aws_access_key_id=$aws_access_key_id -es aws_secret_access_key=$aws_secret_access_key -es spot_account=$spot_account -es spot_token=$spot_token --yum-package python-netaddr --yum-package git -p $(find ~/project/workspace/build/ -name *centos-Core*x86_64.wgn)  ~/project/plugin.yaml
      - run: ecosystem-test upload-plugin -PN aws
      - run: ecosystem-test upload-plugin -PN terraform
      - run: ecosystem-test upload-plugin -PN utilities

  run_eks_test:
    steps:
      - run: ecosystem-test local-blueprint-test -b examples/blueprint.yaml --test-id=spot-ocean-eks -i aws_region_name=me-central-1 -i eks_cluster_name=test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000

jobs:

  cf_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_eks_test

  autoscaleing_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - managerorb/create_manager_container_latest
      - prepare_test_manager

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_version_job
      - node/validate_documentation_job
      - wagonorb/rhel_wagon #:
#          filters:
#            branches:
#              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/wagon #:
#          filters:
#            branches:
#              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon #:
#          filters:
#            branches:
#              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/build_bundle:
#          filters:
#            branches:
#              only: /([0-9\.]*\-build|main|dev)/
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
      - cf_integration_tests_py3:
          requires:
            - wagonorb/build_bundle
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
#          filters:
#            branches:
#              only: /([0-9\.]*\-build|main|dev)/
      - releaseorb/release:
          filters:
            branches:
              only: /main/
          requires:
            - node/unittests_job
            - wagonorb/rhel_wagon
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - node/validate_version_job
            - node/validate_documentation_job
            - cf_integration_tests_py3
      - releaseorb/merge_docs_job:
          filters:
            branches:
              only: /main/
          requires:
            - releaseorb/release
            - node/validate_documentation_job

  sunday_wednesday:
    triggers:
    - schedule:
        cron: "0 3 * * 0,3"
        filters:
          branches:
            only:
              - main
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_version_job
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/build_bundle:
          filters:
            branches:
              only: /main/
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
      - cf_integration_tests_py3:
          requires:
            - wagonorb/build_bundle
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/


  monday_thursday:
    triggers:
    - schedule:
        cron: "0 3 * * 1,4"
        filters:
          branches:
            only:
              - main
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_version_job
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/build_bundle:
          filters:
            branches:
              only: /main/
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
      - cf_integration_tests_py3:
          requires:
            - wagonorb/build_bundle
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/



  tuesday_friday_saturday:
    triggers:
    - schedule:
        cron: "0 3 * * 2,5,6"
        filters:
          branches:
            only:
              - main
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_version_job
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/build_bundle:
          filters:
            branches:
              only: /main/
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
      - cf_integration_tests_py3:
          requires:
            - wagonorb/build_bundle
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/

